# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-14 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
