# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-14 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('RV', 'اضافة'), ('EX', 'سحب')], default='RV', max_length=2)),
            ],
            options={
                'ordering': ('created',),
                'abstract': False,
            },
        ),
    ]
