# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-25 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
