# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-10 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_loan_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='expense',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan', to='expenses.Expense'),
        ),
    ]
