# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-15 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_loan_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('notes', models.TextField(default='')),
                ('expense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custody', to='expenses.Expense')),
            ],
            options={
                'ordering': ('created',),
                'abstract': False,
            },
        ),
    ]
