# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-13 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workeraccount',
            name='password',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
