# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-21 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20181013_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicesparepartrelation',
            name='synced',
        ),
    ]
