# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-23 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_remove_devicesparepartrelation_synced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancedevice',
            name='synced',
            field=models.BooleanField(default=True),
        ),
    ]
