# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-14 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_auto_20181023_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='unit_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
